version: "3.7"
services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    volumes:
      - ./docs/openapi.json:/openapi.json
    environment:
      SWAGGER_JSON: /openapi.json
    ports:
      - 8080:8080
