version: "3"
services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    volumes:
      - ./docs/openapi.json:/usr/share/nginx/html/openapi.json
    environment:
      SWAGGER_JSON: openapi.json
    ports:
      - "8080:8080"
